/*ESSE DB EU FIZ COM O MYSQL WORKBENCH, FUNCIONA NO MEU COMPUTADOR POR SER MARIADB E NO DO DIEGO / RYAN NÃO, POIS USAM ORCLE*/
CREATE DATABASE abex;

CREATE TABLE usuario (
    ID INT PRIMARY KEY auto_increment,
    NOME VARCHAR(255),
    CPF VARCHAR(20),
    EMAIL VARCHAR(255),
    TELEFONE VARCHAR(20),
    SENHA VARCHAR(32),
    ENDERECO VARCHAR(255),
    DATA_REGISTRO DATE,
    NIVEL INT, 
    STATUS INT DEFAULT 1 
);

CREATE TABLE agronomo (
    CREA VARCHAR(20) PRIMARY KEY,
    ID_USUARIO INT,
    CONSTRAINT FK_AGRONOMO_USUARIO FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO (ID)
    ON UPDATE CASCADE
);

CREATE TABLE propriedade (
    ID_PROP INT PRIMARY KEY auto_increment,
    ID_USUARIO INT,
    ID_AGRONOMO VARCHAR(20),
    NOME_PROPRIEDADE VARCHAR(255),
    STATUS BOOLEAN,
    CONSTRAINT FK_PROPRIEDADE_USUARIO FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    
    CONSTRAINT FK_PROPRIEDADE_AGRONOMO FOREIGN KEY (ID_AGRONOMO)
    REFERENCES AGRONOMO (CREA)
    ON UPDATE CASCADE
);

CREATE TABLE micro (
    ID_MICRO INT PRIMARY KEY auto_increment,
    B FLOAT,
    CU FLOAT,
    ZN FLOAT,
    MN FLOAT,
    MO FLOAT,
    FE FLOAT,
    CL FLOAT
);

CREATE TABLE macro (
    ID_MACRO INT PRIMARY KEY auto_increment,
    N FLOAT,
    P FLOAT,
    K FLOAT,
    CA FLOAT,
    MG FLOAT,
    S FLOAT
);

CREATE TABLE analise (
    ID_ANALISE INT PRIMARY KEY auto_increment,
    ID_MICRO INT,
    ID_MACRO INT,
    PH FLOAT,
    TEMPERATURA FLOAT,
    UMIDADE FLOAT,
    DATA_COLETA DATE,
    CONSTRAINT FK_ANALISE_MICRO FOREIGN KEY (ID_MICRO)
    REFERENCES MICRO (ID_MICRO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    
    CONSTRAINT FK_ANALISE_MACRO FOREIGN KEY (ID_MACRO)
    REFERENCES MACRO (ID_MACRO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE relatorio (
    ID_RELATORIO INT PRIMARY KEY auto_increment,
    ID_ANALISE INT,
    DATA_CRIACAO DATE,
    CONSTRAINT FK_RELATORIO_ANALISE FOREIGN KEY (ID_ANALISE)
    REFERENCES ANALISE (ID_ANALISE)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE talhoes (
    ID_TALHAO INT PRIMARY KEY auto_increment,
    DATA_TALHAO DATE,
    ID_ANALISE INT,
    ID_PROPRIEDADE INT,
    CONSTRAINT FK_TALHOES_ANALISE FOREIGN KEY (ID_ANALISE)
    REFERENCES ANALISE (ID_ANALISE)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    
    CONSTRAINT FK_TALHOES_PROPRIEDADE FOREIGN KEY (ID_PROPRIEDADE)
    REFERENCES PROPRIEDADE (ID_PROP)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE dispositivo (
    ID_DISPOSITIVO INT PRIMARY KEY auto_increment,
    LOCALIZACAO VARCHAR(255),
    STATUS BOOLEAN,
    ID_RELATORIO INT,
    ID_ANALISE INT,
    CONSTRAINT FK_DISPOSITIVO_RELATORIO FOREIGN KEY (ID_RELATORIO)
    REFERENCES RELATORIO (ID_RELATORIO)
    ON UPDATE CASCADE,
    
    CONSTRAINT FK_DISPOSITIVO_ANALISE FOREIGN KEY (ID_ANALISE)
    REFERENCES ANALISE (ID_ANALISE)
    ON UPDATE CASCADE
);